import styles from '../styles/Home.module.css'
import Link from 'next/Link';



export default function Home() {



  return (
    <div className={styles.container}>
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>

      <main className={styles.main}>
        <h1 className='title '>Hola, bienvenido a la calculadora de Estadística y cálculo diferencial</h1>

        <div className='d-flex justify-content-center'>
          <form>
            <label className='header '>El calculo a realizar, ¿es de datos agrupados o no agrupados?</label> <br />

            <Link href="/Calc1">
              <button
                type='button'
                className="btn btn-primary"

              >
                Datos agrupados
              </button>
            </Link>

            <Link href="/Calc2">
              <button
                type='button'
                className="btn btn-secondary"

              >
                Datos NO agrupados
              </button>
            </Link>

          </form>



        </div>
      </main>

      <footer className={styles.footer}>
        Pie de pagina
      </footer>
    </div>
  )
}
